var map=mapbox.map("map");map.addLayer(mapbox.layer().id(maptile));var alert=document.getElementById("alert"),alert_mobile=document.getElementById("alert_mobile");map.ui.zoomer.add();map.ui.zoombox.add();map.eventHandlers[3].remove();map.setZoomRange(0,19);map.centerzoom({lat:42.372106,lon:-71.116383},15);
var markerLayer=mapbox.markers.layer().features(features).factory(function(a){var e=mapbox.markers.simplestyle_factory(a);MM.addEvent(e,"click",function(e){var b="images/avatars/"+a.properties.author_image+".jpg";alert.innerHTML="";var c=alert.appendChild(document.createElement("h3")),d=document.createElement("div");d.setAttribute("class","author");alert.appendChild(d);alert.appendChild(document.createElement("hr"));var h=alert.appendChild(document.createElement("p"));c.innerHTML=a.properties.titlealert;
var f=document.createElement("img");f.setAttribute("src",b);f.setAttribute("class","avatar");c.appendChild(f);d.innerHTML='<a href="#">'+a.properties.author+"<a>";h.innerHTML=a.properties.descriptionalert;alert_mobile.innerHTML="";c=alert_mobile.appendChild(document.createElement("h3"));d=document.createElement("div");d.setAttribute("class","author");alert_mobile.appendChild(d);alert_mobile.appendChild(document.createElement("hr"));h=alert_mobile.appendChild(document.createElement("p"));c.innerHTML=
a.properties.titlealert;f=document.createElement("img");f.setAttribute("src",b);f.setAttribute("class","avatar");c.appendChild(f);d.innerHTML='<a href="#">'+a.properties.author+"<a>";h.innerHTML=a.properties.descriptionalert;e.stopPropagation();map.ease.location({lat:a.geometry.coordinates[1],lon:a.geometry.coordinates[0]}).zoom(map.zoom()).optimal()});return e});
MM.addEvent(map.parent,"click",function(){alert.innerHTML="";alert.appendChild(document.createElement("p")).innerHTML="<div id= 'mobile_description'>Hey you're on a mobile device! Swipe across the screen for the menu!</div><p><span class='firstcharacter'>W</span>elcome to the online Commencement Map! You\u2019ll find everything you need to fully enjoy Commencement Week here, as we\u2019ve highlighted the best attractions, shops, and restaurants Harvard has to offer. <u>Come back at 6 PM to see our selected Night Venues!</u></p><br><p> Please allow geolocation services prompted at the top of the page, your location is indicated by the <font color ='#FCBB00'>yellow marker</font>. Simply click on the listed locations nearest you to get started!</p>";alert_mobile.innerHTML=
"";alert_mobile.appendChild(document.createElement("p")).innerHTML="<div id= 'mobile_description'>Hey you're on a mobile device! Swipe across the screen for the menu!</div><p><span class='firstcharacter'>W</span>elcome to the online Commencement Map! You\u2019ll find everything you need to fully enjoy Commencement Week here, as we\u2019ve highlighted the best attractions, shops, and restaurants Harvard has to offer. <u>Come back at 6 PM to see our selected Night Venues!</u></p><br><p> Please allow geolocation services prompted at the top of the page, your location is indicated by the <font color ='#FCBB00'>yellow marker</font>. Simply click on the listed locations nearest you to get started!</p>"});
var interaction=mapbox.markers.interaction(markerLayer);map.addLayer(markerLayer);var geomarkerLayer=mapbox.markers.layer(),geointeraction=mapbox.markers.interaction(geomarkerLayer);map.addLayer(geomarkerLayer);var geolocate=document.getElementById("geolocate");
navigator.geolocation?onload=function(a){a.preventDefault();a.stopPropagation();navigator.geolocation.watchPosition(function(a){geomarkerLayer.features([{geometry:{coordinates:[a.coords.longitude,a.coords.latitude]},properties:{"marker-color":"#FEBC00",description:"You are here!"}}])},function(){geolocate.innerHTML='<h4 style="color: #BA0600;">Position could not be found. Please enable geolocation services on your device.</h4>'})}:geolocate.innerHTML="geolocation is not available";
function tooltipdisplay(a){var e="images/avatars/"+markerLayer.markers()[a].data.properties.author_image+".jpg";alert.innerHTML="";var g=alert.appendChild(document.createElement("h3")),b=document.createElement("div");b.setAttribute("class","author");alert.appendChild(b);alert.appendChild(document.createElement("hr"));var c=alert.appendChild(document.createElement("p"));g.innerHTML=markerLayer.markers()[a].data.properties.titlealert;var d=document.createElement("img");d.setAttribute("src",e);d.setAttribute("class",
"avatar");g.appendChild(d);b.innerHTML='<a href="#">'+markerLayer.markers()[a].data.properties.author+"<a>";c.innerHTML=markerLayer.markers()[a].data.properties.descriptionalert;e="images/avatars/"+markerLayer.markers()[a].data.properties.author_image+".jpg";alert_mobile.innerHTML="";g=alert_mobile.appendChild(document.createElement("h3"));b=document.createElement("div");b.setAttribute("class","author");alert_mobile.appendChild(b);alert_mobile.appendChild(document.createElement("hr"));c=alert_mobile.appendChild(document.createElement("p"));
g.innerHTML=markerLayer.markers()[a].data.properties.titlealert;d=document.createElement("img");d.setAttribute("src",e);d.setAttribute("class","avatar");g.appendChild(d);b.innerHTML='<a href="#">'+markerLayer.markers()[a].data.properties.author+"<a>";c.innerHTML=markerLayer.markers()[a].data.properties.descriptionalert;markerLayer.markers()[a].showTooltip();map.ease.location({lat:markerLayer.markers()[a].location.lat,lon:markerLayer.markers()[a].location.lon}).zoom(17).optimal();return!1}
var onscreen=document.getElementById("onmap"),onscreen_mobile=document.getElementById("onmap_mobile");
map.addCallback("drawn",function(){for(var a=markerLayer.markers(),e=[],g=[],b=0;b<a.length;b++){var c=geomarkerLayer.markers()[0].data.geometry.coordinates[1],d=geomarkerLayer.markers()[0].data.geometry.coordinates[0],h=a[b].data.geometry.coordinates[1],f=(h-c)*(Math.PI/180),d=(a[b].data.geometry.coordinates[0]-d)*(Math.PI/180),c=Math.sin(f/2)*Math.sin(f/2)+Math.cos(c*(Math.PI/180))*Math.cos(h*(Math.PI/180))*Math.sin(d/2)*Math.sin(d/2),c=(7917.509282*Math.atan2(Math.sqrt(c),Math.sqrt(1-c))).toFixed(2);
a[b].data.geometry.distance=c}a.sort(function(a,b){return a.data.geometry.distance-b.data.geometry.distance});for(b=0;b<a.length;b++)c=b+1,e.push('<li class="onmap_container" onClick="tooltipdisplay('+b+');"><div><span class="step">'+c+"</span>"+a[b].data.properties.title+'</div><div class="address">'+a[b].data.properties.description+'</div><div class="distance">'+a[b].data.geometry.distance+" mi away </div></li>"),g.push('<li class="onmap_container" onClick="tooltipdisplay('+b+');"><div><span class="step">'+
c+"</span>"+a[b].data.properties.title+'</div><div class="address">'+a[b].data.properties.description+'</div><div class="distance">'+a[b].data.geometry.distance+" mi away </div></li>");onscreen.innerHTML=e.join("\n");onscreen_mobile.innerHTML=g.join("\n")});